namespace PasswordPal.UI.Common;

public class Constants
{
	public const char PASSWORD_CHAR = '*';
	public const string MESSAGE_BOX_TITLE_ERROR = "Error!";
	public const string MESSAGE_BOX_TITLE_SUCCESS = "Success!";
	public const string HELP_LABEL_TEXT_LOGIN_FORM = "To get started, you have two options:\r\n\r\nIf you already have an account, simply enter your username and password in the designated textboxes and click the \"Login\" button.\r\n\r\nYou'll be securely logged into your account, where you can access your personalized content.\r\n\r\nIf you are new to our platform, click the \"Sign Up\" button to create a new account. Fill in the required details, choose a strong password,\r\n\r\nand hit \"Sign Up\" to register. Once you have your account, you can enjoy all the benefits our application has to offer.";
	public const string HELP_LABEL_TEXT_REGISTRATION_FORM = "Registering is quick and easy. Simply fill in the following fields and click \"Register\" to create your account:\r\n\r\nUsername:\r\nChoose a unique username for your account.\r\n\r\nEmail:\r\nProvide your email address for account communication and password recovery.\r\n\r\nPassword:\r\nCreate a strong and secure password for your account.\r\n\r\nConfirm Password:\r\nRe-enter your password to ensure accuracy.\r\n\r\nOnce you've completed the form, click the \"Register\" button to create your account. Your information will be securely stored, and you'll gain access\r\nto our exciting features.";
	public const string HELP_LABEL_TEXT_STORED_PASSWORDS_FORM = "This page offers powerful features to manage your passwords efficiently:\r\n\r\nViewing Passwords:\r\nThe data grid view displays all your stored passwords. Easily browse through your passwords and view important details in a user-friendly format.\r\n\r\nAdding a New Password:\r\nTo add a new password, simply click the \"Add Item\" button. Enter the details for the new password in the pop up window.\r\n\r\nUpdating Passwords:\r\nTo update a password, select the desired row. Click the \"Update\" button, and a window will appear, enabling you to modify the\r\npassword's details.\r\n\r\nDeleting Passwords:\r\nTo remove a password from your list, select the corresponding row and press the \"Delete\" button.\r\n\r\nLogging Out:\r\nClick the \"Logout\" button to sign out from your account securely.";
	public const string HELP_LABEL_TEXT_CREATE_PASSWORD_FORM = "Here, you can effortlessly add new passwords to your secure vault. Complete the following fields and click \"Save\" to store your password securely:\r\n\r\nTitle:\r\nEnter a descriptive title or name for the password entry. This will help you quickly identify the account associated with the password.\r\n\r\nUsername:\r\nInput the username or login ID associated with the account.\r\n\r\nPassword:\r\nFill in the password for the respective account. Rest assured that it will be encrypted and protected.\r\n\r\nWebsite:\r\nProvide the website URL associated with the account. This way, you can easily access the site directly from the password entry.\r\n\r\nCategory:\r\nChoose the appropriate category from the drop-down list. Organize your passwords by categories for easy retrieval.";
}